/* csp-hashes.mjs — SHA-256 of every inline <script> in the shells.
 *
 * WHY HASHES AND NOT 'unsafe-inline'
 * ----------------------------------
 * An external audit's security checklist asks for a strict CSP with no
 * unsafe-inline, and it is right: `script-src 'self' 'unsafe-inline'` permits
 * any injected <script> the page can be made to contain, which is most of what
 * a CSP is for.
 *
 * Two of these scripts cannot move to a file. The theme bootstrap has to run
 * INLINE AND BLOCKING or the page paints the wrong ground and then flips — its
 * own comment says so, and a deferred script is by definition after the paint.
 * A hash keeps it inline and still refuses everything else.
 *
 * WHY THIS IS GENERATED AND CHECKED
 * ---------------------------------
 * A hash is a copy of the script, and copies drift. Editing an inline script
 * without regenerating produces a CSP that blocks the site's own code — a
 * white page, in production, from a security control. So the generated file is
 * committed, the deploy regenerates it, and test/guard.mjs asserts it matches
 * the committed HTML. A stale hash fails the build instead of the page.
 *
 * `type="application/ld+json"` blocks are NOT included: they are CSP data
 * blocks, never executed, and hashing them would add an entry that authorises
 * nothing.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const SHELLS = ["public/index.html", "public/gems.html"];

export function inlineHashes() {
  const out = new Set();
  for (const f of SHELLS) {
    const html = readFileSync(new URL("../" + f, import.meta.url), "utf8");
    for (const m of html.matchAll(/<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g)) {
      const attrs = m[1] || "";
      const type = (attrs.match(/\btype\s*=\s*["']([^"']+)["']/) || [])[1] || "";
      // Executable only. A ld+json data block is not script-src's business.
      if (type && !/^(text\/javascript|module|application\/javascript)$/i.test(type)) continue;
      out.add("sha256-" + createHash("sha256").update(m[2], "utf8").digest("base64"));
    }
  }
  return [...out].sort();
}

/* ── IMPORTING THIS MUST NOT WRITE ANYTHING ─────────────────────────────────
 * test/guard.mjs imports inlineHashes() to check the committed file against
 * the real scripts. When the write ran at module top level, that import
 * REGENERATED the file first and the check then compared it with itself — it
 * passed on a deliberately drifted script, which is a guard that cannot fail.
 * Caught by trying to break it. The write now happens only when this file is
 * the entry point. */
function generate() {
const hashes = inlineHashes();
const body = `/* GENERATED by scripts/csp-hashes.mjs — do not edit.
 * SHA-256 of every inline <script> in the shells, so the Content-Security
 * Policy can name them exactly instead of allowing 'unsafe-inline'.
 * Regenerate with \`node scripts/csp-hashes.mjs\`; test/guard.mjs fails the
 * build if this file and the HTML disagree. */
export const INLINE_SCRIPT_HASHES = ${JSON.stringify(hashes, null, 2)};
`;
writeFileSync(new URL("../src/csp-hashes.js", import.meta.url), body);
console.log(`csp-hashes: ${hashes.length} inline script${hashes.length === 1 ? "" : "s"} hashed`);
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  generate();
}
