#!/usr/bin/env node
/**
 * route-meta.mjs — the Worker's copy of signal.js's per-route titles.
 *
 * signal.js owns META: one [title, description] per route, written into the
 * head on every client render. The Worker now writes the same head into the
 * HTML before JavaScript runs (src/seo.js), and a second hand-kept table would
 * drift from the first — the fault this repo has fixed more than once. So the
 * table is EXTRACTED from signal.js into src/route-meta.js, and guard.mjs fails
 * the build if the committed copy no longer matches.
 *
 *   node scripts/route-meta.mjs          write src/route-meta.js
 *   node scripts/route-meta.mjs --check  exit 1 if it is stale
 */
import { readFileSync, writeFileSync } from "node:fs";

export function extractMeta(js) {
  const i = js.indexOf("const META = {");
  if (i < 0) throw new Error("route-meta: `const META = {` not found in signal.js");
  let depth = 0, j = js.indexOf("{", i), inStr = null, esc = false;
  for (; j < js.length; j++) {
    const ch = js[j], nx = js[j + 1];
    if (inStr) {
      if (esc) { esc = false; continue; }
      if (ch === "\\") { esc = true; continue; }
      if (ch === inStr) inStr = null;
      continue;
    }
    if (ch === "/" && nx === "*") { j = js.indexOf("*/", j + 2) + 1; continue; }
    if (ch === "/" && nx === "/") { j = js.indexOf("\n", j); continue; }
    if (ch === "'" || ch === '"' || ch === "`") { inStr = ch; continue; }
    if (ch === "{") depth++;
    if (ch === "}" && --depth === 0) break;
  }
  const lit = js.slice(js.indexOf("{", i), j + 1);
  // A literal of strings and comments only — our own file, evaluated at build.
  return new Function(`return (${lit});`)();
}

const meta = extractMeta(readFileSync("public/signal.js", "utf8"));
const out = `/* GENERATED by scripts/route-meta.mjs from META in public/signal.js — do not edit.\n   guard.mjs fails the build if this falls out of step. */\nexport const SIGNAL_META = ${JSON.stringify(meta, null, 1)};\n`;
if (process.argv.includes("--check")) {
  let cur = ""; try { cur = readFileSync("src/route-meta.js", "utf8"); } catch { /* missing */ }
  if (cur !== out) { console.error("route-meta: src/route-meta.js is stale — run node scripts/route-meta.mjs"); process.exit(1); }
  console.log(`route-meta: ${Object.keys(meta).length} routes, in step`);
} else {
  writeFileSync("src/route-meta.js", out);
  console.log(`route-meta: ${Object.keys(meta).length} routes → src/route-meta.js`);
}
