/* GENERATED by scripts/csp-hashes.mjs — do not edit.
 * SHA-256 of every inline <script> in the shells, so the Content-Security
 * Policy can name them exactly instead of allowing 'unsafe-inline'.
 * Regenerate with `node scripts/csp-hashes.mjs`; test/guard.mjs fails the
 * build if this file and the HTML disagree. */
export const INLINE_SCRIPT_HASHES = [
  "sha256-2rD94fNFgdL/uSOx8uH+lGPnKd6nM7EpJf0fWO2sKxc=",
  "sha256-R58bQ6E9E3IIHQnuL4zHVM8lQgy8mfV8DIG40DSAqkY=",
  "sha256-X83CC0BX3Vy99+K20P3I5gzaaha/UyBisIgC/Zx062c=",
  "sha256-ly02Vl/T4fFdeXcuub6QTwxx4UYUUhQ7GAKPo6lvyJo="
];
