/* GENERATED by scripts/route-meta.mjs from META in public/signal.js — do not edit.
   guard.mjs fails the build if this falls out of step. */
export const SIGNAL_META = {
 "/": [
  "Signal — Indian markets, every morning",
  "Nifty breadth, sector heat, IPO books open now, ranked trade ideas and a public signal ledger. India’s markets in one screen, rebuilt before every open."
 ],
 "/markets": [
  "Markets — the board, 71 instruments with a year of context",
  "Indices, sectors, commodities and currencies on one board, each against its own 52-week range. Sector heat, breadth and what moved today."
 ],
 "/screen": [
  "Screen — every NSE name we track, filterable",
  "Every name in the universe on price, trend, quality, value and institutional flow. FII and DII holding quarter on quarter, from the company’s own filings."
 ],
 "/signals": [
  "Signals — the public ledger, wins and losses both",
  "Every call this book has published, open and closed, with the entry, stop and targets it was sent with and what it actually did."
 ],
 "/heat": [
  "The heatmap — today in each name’s own units",
  "The market coloured by how far each name moved against its own average range rather than in percent, outlined by the screen’s standing call, and marked where a name is in today’s wire."
 ],
 "/map": [
  "The map — every NSE name on one screen",
  "The whole screened market as one picture, coloured by the call, momentum, value, quality, position in its year, or how often each name has risen in this calendar month over eleven years."
 ],
 "/reads": [
  "Weekly reads — seven companies, studied properly",
  "One company per sector, every Saturday. What it sells, how the money arrives, and what would break it."
 ],
 "/discover": [
  "Discover — every way into the screened names",
  "Each section of this site, what question it answers, and which of the same screened names it is looking at."
 ],
 "/radar": [
  "Signal radar — the market, and the names carrying it",
  "A breadth-based market score with every term printed, and the eight highest-scoring names ranked on trend, momentum, volume and institutional flow."
 ],
 "/engines": [
  "The floor — every engine, what fires it, what it has done",
  "Every engine with its trigger conditions, where each stop comes from, how it can be wrong, and its measured record. Nothing is cleared for capital."
 ],
 "/ideas": [
  "Ideas — this week’s multibaggers and what they were picked at",
  "The weekly leadership screen, with the price each name was picked at and what it has done since."
 ],
 "/ipo": [
  "IPO — books open now, and how last year’s listings did",
  "Issues open and upcoming with demand, valuation and peer comparison, plus every recent listing measured against its issue price."
 ],
 "/news": [
  "News — the wire, and the screened names each story touches",
  "Market news filtered to what touches the NSE screen, with the companies each story affects."
 ],
 "/funds": [
  "Funds — SIP screen over AMFI NAV, Direct plans only",
  "Mutual funds ranked on three- and five-year return against their own drawdown and volatility. Direct plans only, because the cost difference compounds."
 ],
 "/watch": [
  "Watchlist — your names, sorted by what needs attention",
  "The names you follow, ranked by what changed rather than alphabetically."
 ],
 "/brief": [
  "Today’s brief — one setup, in full",
  "The highest-scoring open signal, with every figure behind it: levels, evidence, what would invalidate it, and the engine’s own record."
 ],
 "/methodology": [
  "Methodology — how every number here is made",
  "Every engine, every score, every stop and target rule, and the sample size behind each claim."
 ],
 "/sources": [
  "Data sources — where each number comes from",
  "The feed behind every figure on this site, and how fresh each one is."
 ],
 "/terms": [
  "Terms",
  "Terms of use for signal.askakshay.com."
 ],
 "/privacy": [
  "Privacy",
  "What this site stores, and what it does not."
 ],
 "/join": [
  "The morning list",
  "Join the list for the daily email. It is not being sent yet; the brief is on the site every morning."
 ],
 "/research": [
  "The research floor — three engines, and the record that rejects them",
  "BUOY, ANCHOR and BEDROCK: unproven engines published with their own measured null results beside every name."
 ],
 "/buoy": [
  "BUOY — the 200-period average, reclaimed on the 4-hour",
  "A fallen name closing a 4-hour candle back above its 200-period average, with momentum already turning. Measured over two years, and the measurement says no edge."
 ],
 "/about": [
  "About — who builds Signal, and why it publishes its losses",
  "Signal is built by Akshay Kothari, a Chartered Accountant working in FP&A: what the site is, what it is not, and why its ledger is not curated."
 ],
 "/disclaimer": [
  "Disclaimer — educational research, not investment advice",
  "Signal is not registered with SEBI as a Research Analyst or Investment Adviser. Nothing on it is a recommendation or personalised advice."
 ],
 "/disclosures": [
  "Disclosures — conflicts, incentives and who pays for this",
  "Who pays for Signal (nobody), personal positions, employment, and the conflict of an author grading his own engines — stated plainly."
 ],
 "/404": [
  "Not found — signal.askakshay.com",
  "There is no page at this address."
 ]
};
